export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from "./components/navbar"
import Sidebar from "./components/sidebar"
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
